find_path(OPENNI2_INCLUDE_DIR OpenNI.h $ENV{OPENNI2_INCLUDE})

message (${OPENNI2_INCLUDE_DIR})

find_library(OPENNI2_LIBRARY NAMES OpenNI2
             HINTS $ENV{OPENNI2_REDIST} )

set(OPENNI2_LIBRARIES ${OPENNI2_LIBRARY} )
set(OPENNI2_INCLUDE_DIRS ${OPENNI2_INCLUDE_DIR} )
if (OPENNI2_INCLUDE_DIR)
  set(OPENNI2_FOUND true)
endif(OPENNI2_INCLUDE_DIR)